/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema for SunSpec information model definition
 */
export interface Schema {
  comments?: string[];
  desc?: string;
  detail?: string;
  group: Group;
  id: number;
  label?: string;
  notes?: string;
  [k: string]: unknown;
}
export interface Group {
  comments?: string[];
  count?: number | string;
  desc?: string;
  detail?: string;
  groups?: Group[];
  label?: string;
  name: string;
  notes?: string;
  points?: Point[];
  type: "group" | "sync";
  [k: string]: unknown;
}
export interface Point {
  access?: "R" | "RW";
  comments?: string[];
  count?: number;
  desc?: string;
  detail?: string;
  label?: string;
  mandatory?: "M" | "O";
  name: string;
  notes?: string;
  sf?: number | string;
  size: number;
  static?: "D" | "S";
  symbols?: Symbol[];
  type:
    | "int16"
    | "int32"
    | "int64"
    | "raw16"
    | "uint16"
    | "uint32"
    | "uint64"
    | "acc16"
    | "acc32"
    | "acc64"
    | "bitfield16"
    | "bitfield32"
    | "bitfield64"
    | "enum16"
    | "enum32"
    | "float32"
    | "float64"
    | "string"
    | "sf"
    | "pad"
    | "ipaddr"
    | "ipv6addr"
    | "eui48"
    | "sunssf"
    | "count";
  units?: string;
  value?: number | string;
  [k: string]: unknown;
}
export interface Symbol {
  comments?: string[];
  desc?: string;
  detail?: string;
  label?: string;
  name: string;
  notes?: string;
  value: unknown;
  [k: string]: unknown;
}
